# Generated by Django 3.2.8 on 2021-10-06 22:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Options', 'Poll Options')], default='Job', max_length=15)),
                ('by', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Options', 'Poll Options')], default='Job', max_length=15)),
                ('by', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Options', 'Poll Options')], default='Job', max_length=15)),
                ('by', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Options', 'Poll Options')], default='Job', max_length=15)),
                ('by', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Job', 'Job'), ('Story', 'Story'), ('Comment', 'Comment'), ('Poll', 'Poll'), ('Poll Options', 'Poll Options')], default='Job', max_length=15)),
                ('by', models.CharField(blank=True, max_length=20, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('dead', models.BooleanField(default=False)),
                ('kids', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
