# Generated by Django 3.2.8 on 2021-10-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20211006_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='type',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='story',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
