# Generated by Django 3.2.8 on 2021-10-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211007_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='descendants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poll',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='parent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polloption',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='descendants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
