# Generated by Django 3.2.8 on 2021-10-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20211010_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='polloption',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
